openapi: 3.1.0
info:
  title: Twelve Data API
  description: Ottiene dati di mercato in tempo reale, storici, indicatori tecnici, fondamentali ed economici da Twelve Data.
  version: 1.0.0
servers:
  - url: "https://api.twelvedata.com"

paths:
  /time_series:
    get:
      operationId: getTimeSeries
      summary: Ottiene dati di mercato in tempo reale o storici
      parameters:
        - name: symbol
          in: query
          required: true
          description: Simbolo dell'asset (es. AAPL per Apple, BTC/USD per Bitcoin)
          schema:
            type: string
        - name: interval
          in: query
          required: true
          description: Intervallo di tempo (es. 1min, 5min, 15min, 1h, 1day)
          schema:
            type: string
        - name: apikey
          in: query
          required: true
          description: e7ec230473a741cfafc072e7fe54172e
          schema:
            type: string
      responses:
        '200':
          description: Dati di mercato
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      symbol:
                        type: string
                      interval:
                        type: string
                      currency:
                        type: string
                  values:
                    type: array
                    items:
                      type: object
                      properties:
                        datetime:
                          type: string
                        open:
                          type: string
                        high:
                          type: string
                        low:
                          type: string
                        close:
                          type: string
                        volume:
                          type: string

  /quote:
    get:
      operationId: getQuote
      summary: Ottiene le quotazioni di mercato in tempo reale
      parameters:
        - name: symbol
          in: query
          required: true
          description: Simbolo dell'asset (es. AAPL, BTC/USD)
          schema:
            type: string
        - name: apikey
          in: query
          required: true
          description: e7ec230473a741cfafc072e7fe54172e
          schema:
            type: string
      responses:
        '200':
          description: Quotazioni in tempo reale
          content:
            application/json:
              schema:
                type: object
                properties:
                  symbol:
                    type: string
                  price:
                    type: string
                  change:
                    type: string
                  percent_change:
                    type: string
                  high:
                    type: string
                  low:
                    type: string
                  open:
                    type: string
                  previous_close:
                    type: string

  /technical_indicator:
    get:
      operationId: getTechnicalIndicators
      summary: Calcola indicatori tecnici per un asset
      parameters:
        - name: symbol
          in: query
          required: true
          description: Simbolo dell'asset (es. AAPL, BTC/USD)
          schema:
            type: string
        - name: interval
          in: query
          required: true
          description: Intervallo di tempo (es. 1min, 5min, 15min, 1h, 1day)
          schema:
            type: string
        - name: indicator
          in: query
          required: true
          description: Nome dell'indicatore tecnico (es. RSI, MACD, Bollinger Bands)
          schema:
            type: string
        - name: apikey
          in: query
          required: true
          description: e7ec230473a741cfafc072e7fe54172e
          schema:
            type: string
      responses:
        '200':
          description: Dati degli indicatori tecnici
          content:
            application/json:
              schema:
                type: object
                properties:
                  values:
                    type: array
                    items:
                      type: object
                      properties:
                        datetime:
                          type: string
                        value:
                          type: string

  /fundamentals:
    get:
      operationId: getFundamentals
      summary: Ottiene dati fondamentali di un'azienda
      parameters:
        - name: symbol
          in: query
          required: true
          description: Simbolo dell'azione (es. AAPL, TSLA)
          schema:
            type: string
        - name: apikey
          in: query
          required: true
          description: e7ec230473a741cfafc072e7fe54172e
          schema:
            type: string
      responses:
        '200':
          description: Dati fondamentali dell'azienda
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  sector:
                    type: string
                  industry:
                    type: string
                  market_cap:
                    type: string
                  pe_ratio:
                    type: string
                  eps:
                    type: string

  /economic_data:
    get:
      operationId: getEconomicData
      summary: Ottiene dati macroeconomici globali
      parameters:
        - name: country
          in: query
          required: true
          description: Nome del paese (es. US, EU, CN)
          schema:
            type: string
        - name: indicator
          in: query
          required: true
          description: Tipo di dato economico (es. GDP, Inflation, Unemployment)
          schema:
            type: string
        - name: apikey
          in: query
          required: true
          description: e7ec230473a741cfafc072e7fe54172e
          schema:
            type: string
      responses:
        '200':
          description: Dati macroeconomici globali
          content:
            application/json:
              schema:
                type: object
                properties:
                  country:
                    type: string
                  indicator:
                    type: string
                  value:
                    type: string
                  datetime:
                    type: string
